dtype: "bf16"
learning_rate: 1e-6
batch_size: 64
accumulation_steps: 1
grad_clip: 1.0
epochs: 2

# model
base_model_path: "final/myna_25M_pretrain"
 
# LoRA/QLoRA
lora: null            # null | "train" | "path/to/adapter"
lora_r: 16
lora_alpha: 32
lora_dropout: 0.05
target_modules: ["q_proj","k_proj","v_proj","o_proj","gate_proj","up_proj","down_proj"]
use_qlora: false
load_in_4bit: true
bnb_4bit_compute_dtype: "bfloat16"  # or "float16"
bnb_4bit_quant_type: "nf4"          # or "fp4"

# logging
use_swanlab: True
swanlab_project: "Myna-SFT-2"
log_interval: 100

# save
save_dir: "./outputs/checkpoints/sft"
save_weight: "full_sft"
save_interval: 50000
tokenizer_path: "final/myna_25M_sft"
model_path: "final/myna_25M_sft"

# data
data_path: "../minimind/dataset/sft_mini_512.jsonl"
max_seq_len: 512
num_workers: 8